version: '3.8'

services:
  webpaladin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webpaladin-prod
    image: webpaladin:production
    volumes:
      # Mount scan results directory to persist data
      - ./scan_results:/app/scan_results
      # Mount Nmap files directory
      - ./Nmap-reports-files:/app/Nmap-reports-files:ro
      # Mount logs directory
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
      - PRODUCTION=1
    stdin_open: false
    tty: false
    # Run as privileged to allow network scanning
    privileged: true
    # Add network capabilities for scanning
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Restart policy for production
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: webpaladin-network-prod
    driver: bridge 